### ISSUE TITLE
Suggestion: Make version tag

### ISSUE THREAD

**Issue by stefanuros** [wrzonki/deno-crone#1]
Hi, Im using this library and would like to use the current version without worrying about any changes that might be made to it. Can you make a version tag on the current state of the module? Also, the import in the readme example has misspelled `cron` as `crone`.

**Comment by wrzonki** [comment]
Hey,
I [added this changes](https://github.com/wrzonki/deno-cron/blob/master/CHANGELOG.md)

Now you should be able to just impot it from this link:
> https://deno.land/x/cron@v.0.0.1/cron.ts


I know that this is not perfect solution, but I've tested few package managers, and unfortunatly none was working for me (dem, bump). If you have something that works let me know, I will be happy to implement :)

Thanks for contribute!

**Comment by stefanuros** [comment]
This is great. Thanks!
